### ISSUE TITLE
Tests fail on Node.js 4, 6 and 7

### ISSUE THREAD

**Issue by daviddias** [indutny/http-deceiver#2]
Investigate

```
 ⭠ master ⮀ ~/code/http-deceiver ⮀
» npm test

> http-deceiver@1.2.7 test /Users/ground-control/code/http-deceiver
> mocha --reporter=spec test/*-test.js



  HTTP Deceiver
    ✓ should emit request
    ✓ should emit response
    ✓ should override .execute and .finish
    ✓ should work with reusing parser
    ✓ should emit CONNECT request
    ✓ should emit Upgrade request
    1) should emit Upgrade response


  6 passing (27ms)
  1 failing

  1) HTTP Deceiver should emit Upgrade response:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at ClientRequest.<anonymous> (test/api-test.js:209:7)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at HTTPParser.execute (lib/deceiver.js:115:31)
      at Socket.socketOnData (_http_client.js:363:20)
      at Deceiver._emitEmpty (lib/deceiver.js:242:17)
      at Deceiver.emitResponse (lib/deceiver.js:127:10)
      at test/api-test.js:217:16
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

Makes https://github.com/indutny/http-deceiver/issues/1 even more valuable

**Comment by jaredsmith** [comment]
Any status update on fixing this?
